### ISSUE TITLE
Install Failure on all operating systems

### ISSUE THREAD

**Issue by jshearman21** [hoburg/gpkit#509]
On a clean install, ended up with this message:

```
dhcp-18-111-35-65:~ jake2$ python -c "import gpkit.tests; gpkit.tests.run()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jake2/anaconda/lib/python2.7/site-packages/gpkit/__init__.py", line 84, in <module>
    enable_units()
  File "/Users/jake2/anaconda/lib/python2.7/site-packages/gpkit/__init__.py", line 40, in enable_units
    UNIT_REGISTRY = pint.UnitRegistry(path)
  File "/Users/jake2/anaconda/lib/python2.7/site-packages/pint/unit.py", line 526, in __init__
    self.load_definitions(filename)
  File "/Users/jake2/anaconda/lib/python2.7/site-packages/pint/unit.py", line 768, in load_definitions
    raise ValueError('While opening {0}\n{1}'.format(file, msg))
ValueError: While opening /Users/jake2/anaconda/lib/python2.7/site-packages/gpkit/gpkit_units.txt
[Errno 2] No such file or directory: '/Users/jake2/anaconda/lib/python2.7/site-packages/gpkit/gpkit_units.txt'
```

**Comment by whoburg** [comment]
@bqpd: lots of people have this issue. Looks like gpkit_units is missing from pip installs. Does it need to be added to `MANIFEST`?

**Comment by whoburg** [comment]
@KirchnerFH

**Comment by bqpd** [comment]
Danggg yes it does. Sorry should have checked that this morning D: this is what happens when I don't go through the new version checklist.

**Comment by bqpd** [comment]
Confirmed working now.

**Comment by whoburg** [comment]
@jshearman21 and @KirchnerFH: this should work now if you reinstall.

**Comment by KirchnerFH** [comment]
@whoburg I still can't the program to install  and run without errors. When I run the tests, I have 16 error messages that all finish with ``ValueError: Unknown solver ' ' ``.  Do you know if this is a related program issue or have I just incorrectly installed something?

```
ERROR: test_simpleflight_ (gpkit.tests.t_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fritz_kirchner/cvxopt/examples/doc/chap8/gpkit/gpkit/tests/t_examples.py", line 130, in test
    IMPORTED_EXAMPLES[name] = importlib.import_module(name)
  File "/Users/fritz_kirchner/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/fritz_kirchner/cvxopt/examples/doc/chap8/gpkit/docs/source/examples/simpleflight.py", line 55, in <module>
    sol = m.solve(verbosity=1)
  File "/Users/fritz_kirchner/cvxopt/examples/doc/chap8/gpkit/gpkit/model.py", line 342, in solve
    *args, **kwargs)
  File "/Users/fritz_kirchner/cvxopt/examples/doc/chap8/gpkit/gpkit/model.py", line 500, in _solve
    result = solvefn(*args, **kwargs)
  File "/Users/fritz_kirchner/cvxopt/examples/doc/chap8/gpkit/gpkit/geometric_program.py", line 128, in solve
    raise ValueError("Unknown solver '%s'." % solver)
ValueError: Unknown solver ''.

----------------------------------------------------------------------
Ran 82 tests in 0.310s

FAILED (errors=16)
```

**Comment by bqpd** [comment]
Looks like it didn't properly find solver during the installation. Try running `python -c "import gpkit.build; gpkit.build.build_gpkit()`, and then run the tests again.

**Comment by KirchnerFH** [comment]
I ran the above ```python -c "import gpkit.build; gpkit.build.build_gpkit()"``` and this is what was executed:
```
Could not load settings file.
#     Could not find __init__.py
Started building gpkit...

Attempting to find and build solvers:

# Looking for cvxopt
#   Trying to import cvxopt...
# Found cvxopt in Python path
# Looking for mosek
# Did not find mosek
# Looking for mosek_cli
#   Trying to run mskexpopt...
#     Calling 'mskexpopt'
##
### CALL BEGINS
/bin/sh: mskexpopt: command not found
### CALL ENDS
##
# Did not find mosek_cli
...finished building gpkit.

Found the following solvers: cvxopt
#     Replacing directory gpkit/env
Replaced the directory gpkit/env
```

But I still have the same errors as before when I run the tests.

**Comment by whoburg** [comment]
Try this workaround:

1. start ipython
2. `import gpkit` (results in "Could not load settings file." message)
3. Check the value of `gpkit.__file__`
4. cd into the directory containing `gpkit.__file__`.
5. Run `import gpkit.build; gpkit.build.build_gpkit()`
6. Test install. Has worked in every case so far.

Please report back and let us know if it works. Apologies for the inconvenience while we get our installation process straightened out for all operating systems.

**Comment by whoburg** [comment]
This seems to happen on every single new install regardless of operating system. It seems the key step to fix the issue is cd'ing into the directory containing `gpkit.__file__`.

Is there something in the build script or our PyPI settings that could be causing this?

**Comment by bqpd** [comment]
Works fine on linux. I should grab a mac / python xy laptop and test.

**Comment by whoburg** [comment]
@galbramc: would it be possible to set up a CI machine to test a new pip install as described in our install docs, as opposed to installing by cloning the git repo?

**Comment by galbramc** [comment]
Sure. I'll install it into a virtualenv and run the tests.

**Comment by bqpd** [comment]
Great plan! Could we trigger it somehow on push commits that contain "pypi"?

**Comment by galbramc** [comment]
Possibly. There are many ways to trigger a build. I don't know if we can get pypi to send the trigger, but we can always send our own curl command to Jenkins to trigger the build.

**Comment by galbramc** [comment]
What is the process to upload to pypi?

**Comment by bqpd** [comment]
A single python command, so I can just switch to a two-line bash script

**Comment by galbramc** [comment]
Sure that will work. Give me some time to setup the job. I'll call it gpkit_Install

**Comment by galbramc** [comment]
So I have things setup now, are you planning on putting this bash script in the repo?

**Comment by galbramc** [comment]
The curl command involves a "secret token" so that random people can't trigger the build. I'm reluctant to put the "secret token" in a public repository. I instead turned on URL mointoring. Jenkins is now monitoring for changes at this URL: https://pypi.python.org/pypi/gpkit/. It checks every 5 min. If there is a change on that website, jenkins will run the install job.

**Comment by bqpd** [comment]
Perfect!

**Comment by galbramc** [comment]
So you might have noticed a large number of builds over night, that's because the polling was not polling the right url. I've changed it now to poll https://pypi.python.org/pypi/gpkit/json which is actually parsable information. I'm currently checking for changes to info.version (which is the latest version number). When that changes things will build.

Btw, it's failing on all systems. Do you expect it to work anywhere? I could have the script setup incorrectly.

**Comment by whoburg** [comment]
Yep (looking at the Macys log), that's the `ValueError: Unknown solver ''.` I've been seeing on all new installs. So getting gpkit_Install to pass will solve this issue and possibly #512!

Thanks @galbramc for setting this up, this is a big help.

**Comment by galbramc** [comment]
I see that error on all systems though, not just OSX

**Comment by whoburg** [comment]
True -- changed the issue title to reflect the scope of the problem.

**Comment by galbramc** [comment]
I also updated the trigger on gpfit_Push to build when a new version of gpkit is pushed to pypi. That way you will know if changes to the gpkit on pypi breaks gpfit.

**Comment by galbramc** [comment]
Oh, I should mention that I noticed the gpkit install does not work with pip 7, but it works with pip 8. You might want to mention the minimum required version of pip in your documentation (unless this is not intentional).

**Comment by whoburg** [comment]
great! thanks for both of these.

**Comment by galbramc** [comment]
Btw, I have no way of checking that the polling really is working correctly until a new version of gpkit is pushed to pypi. So let me know if gpkit_Install does not fire up after 5 min or so once gpkit is updated.

**Comment by whoburg** [comment]
is there a way we can activate the build without pushing versions to pypi for debugging purposes?

**Comment by galbramc** [comment]
That is a pypi question. I did see something about a testpypi.

**Comment by galbramc** [comment]
I think this is what you are looking for: https://testpypi.python.org/pypi

We might need another jenkins job if want it to execute on the testing. Not a big deal if you want it.

**Comment by galbramc** [comment]
So one of the reasons I though there was a difference between pip 7 and 8, was because I saw the build from gpkit when I made the switch. I don't ever see the gpkit build anymore when I run pip install gpkit. I don't know if there is some global file you are looking for to prevent the build or not. Just a thought.

**Comment by whoburg** [comment]
Thanks, that sounds potentially related to #509, where we also seem to be having trouble with the build script not getting run.

**Comment by galbramc** [comment]
Looks like the install works correctly if you tell pip to ignore the cache, i.e.

pip install --no-cache-dir gpkit

this seems to successfully install gpkit, but including the cache causes a failure.

**Comment by galbramc** [comment]
So I did a little bit or reading, and it looks like you might just need to add

```python
import setuptools
```

to your setup.py file and this will get fixed (maybe). pip runs the command: python setup.py bdist_wheel, and that seems to only work when you import setuptools.

**Comment by bqpd** [comment]
@whoburg, should I put that line in a push a dummy version up?

**Comment by galbramc** [comment]
How about you push it to the testing site: https://testpypi.python.org/pypi

**Comment by bqpd** [comment]
Any number of install/uninstalls seem to work on my machine. :-/

**Comment by galbramc** [comment]
Create a virtualenv, install gpkit. Blow away the env, and repeat. Does
that work?

**Comment by bqpd** [comment]
I was doing it in a virtualenv, but I'll make a new one.

**Comment by galbramc** [comment]
specifically, run these commands:
```bash
virtualenv venv_test
. venv_test/bin/actiavate
pip install gpkit
python -c 'import gpkit.tests; gpkit.tests.run()'
deactivate
rm -rf venv_test

virtualenv venv_test
. venv_test/bin/actiavate
pip install gpkit
python -c 'import gpkit.tests; gpkit.tests.run()'
```

**Comment by whoburg** [comment]
do we currently have a testing setup that fails due to this issue? (hoping so, so we can see the resolution and make sure it remains fixed)

**Comment by galbramc** [comment]
yes, this test is failing because of the above issue:
https://acdl.mit.edu/csi/job/gpkit_Install/

**Comment by bqpd** [comment]
@galbramc: still works on my computer after those commands.

**Comment by whoburg** [comment]
fresh `pip install gpkit` into a new conda virtualenv on my computer reproduces the `Could not load settings file.` error.

Can be helpful somehow? Should I add `import setuptools` to my local setup.py and run something to determine whether it resolves the issue? I'm not familiar with how to push to PyPI.

**Comment by bqpd** [comment]
Can you get the issue with `pip install GPDIR` in a new virtualenv? That would be the ideal environment to test `import setuptools`

**Comment by whoburg** [comment]
nope, sadly it only occurs for a pip install that actually fetches the remote package

**Comment by bqpd** [comment]
doe s`pip install https://github.com/hoburg/gpkit/archive/master.zip` trigger it?

**Comment by whoburg** [comment]
nope, that does not trigger it.

**Comment by bqpd** [comment]
dang, that seems weird.

**Comment by whoburg** [comment]
though immediately after doing that, in the same virtualenv, I can still trigger it by doing

```
pip uninstall gpkit
pip install gpkit
```

**Comment by bqpd** [comment]
ooh. promising. does setuptools help?

**Comment by whoburg** [comment]
I don't see what that would do -- the version that pip grabs won't have the setuptools change, right?

**Comment by whoburg** [comment]
should we try importing setuptools and pushing that version off to PyPI?

**Comment by bqpd** [comment]
yeah, I think so.

**Comment by bqpd** [comment]
I'll do it from the current master along with the new point release?

**Comment by whoburg** [comment]
any possibility of breaking things by pushing to master? e.g. do the test machines have setuptools? stick it in a try/catch?

You may also get nailed for an unused import pylint warning -- could suppress, or could `assert setuptools`

**Comment by galbramc** [comment]
Well, the good thing is that https://acdl.mit.edu/csi/job/gpkit_Install/ is running every time you push a new version to pipy, but they are still failing. 

Do you really want to push all these versions to pipy? Would it not be better to use the testing site https://testpypi.python.org/pypi

**Comment by galbramc** [comment]
Looks like the settings file is actually fixed, but now you have this error:

```
ImportError: Could not load MOSEK library: ImportError('/home/eburn/.gpkit/expopt.so not found.',)
```

**Comment by bqpd** [comment]
Yeah, it's still just not running the build script, now it's just copying my settings.

**Comment by galbramc** [comment]
How did your settings get to the testing machines? Did you push your settings to pipy?

**Comment by bqpd** [comment]
Yeah. Just pushed a new version without them.

**Comment by galbramc** [comment]
That fixed it. We just ran out of disk space on the OSX VM. Let me see what I can do about that.

**Comment by galbramc** [comment]
Nvm, it is actually still broken. Looks like ".gpkit" is not being created.

**Comment by galbramc** [comment]
Debugging this is realeasing a lot of versions:

``` 
Could not find a version that satisfies the requirement gpkit==xxx (from versions: 0.0.4, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.3.0.1, 0.3.1, 0.3.2, 0.3.2.0, 0.3.2.1, 0.3.3.0, 0.3.4.0, 0.3.4.1, 0.3.4.2, 0.3.4.3, 0.3.4.4, 0.3.4.5, 0.3.4.6, 0.3.4.7, 0.3.4.8, 0.3.4.9, 0.3.4.10, 0.3.5.0, 0.3.5.1, 0.3.5.2, 0.3.5.3, 0.3.5.4)
```

You really really should use the testing site instead. That's what it's for. https://testpypi.python.org/pypi

**Comment by whoburg** [comment]
@bqpd, can you remove from PyPI the versions that were just for debugging?

**Comment by bqpd** [comment]
Yup, done!

**Comment by bqpd** [comment]
@galbramc: the pypi package didn't change the part of the build script that made `~/.gpkit`, so I don't know why it would make that with a manually run build script but not when run by pip.

**Comment by galbramc** [comment]
I didn't realize there was a separate part of the script that created ~/.gpkit. That's not in then.

Did you try adding 
```
import setuptools
```
near the top of setup.py? As you can see here: http://pip-python3.readthedocs.org/en/latest/reference/pip_wheel.html, pip runs

```
python setup.py bdist_wheel -d TARGET
```

which does not work unless you import setuptools. You can also use some guidance there to debug without pushing to pipy.

**Comment by bqpd** [comment]
pip also seems to run `sdist`, and unfortunately I couldn't get `setuptools` to not copy local settings files (which is how my settings ended up on pip earlier today...)

**Comment by galbramc** [comment]
So why not use a clean clone of the repo when you push to pipy where there
isn't a local settings file?

**Comment by whoburg** [comment]
@bqpd let's try @galbramc's suggestion?

 - [ ] Once this is fixed we should merge the `readme` branch to master, to show status for all three Jenkins builds.

**Comment by galbramc** [comment]
Sorry, it is failing on windows. I had --no-cahce-dir for the windoze script which caused the success.

**Comment by galbramc** [comment]
The settings file actually seems to be solved. I just get this error now on the builds:

ImportError: Could not load MOSEK library: ImportError('/home1/jenkins/.gpkit/expopt.so not found.',)

**Comment by galbramc** [comment]
Btw, the power is going to be turned off in the building tonight. So we are going to need to shut down jenkins tonight.

**Comment by whoburg** [comment]
Somehow one of the recent pushes to PyPI caused the settings file to get tracked. @bqpd, any idea how that happened? It's good news, but I'd like to know what fixed the problem.

**Comment by whoburg** [comment]
I think we can close this after merging #564 (I'd still like to know what caused the settings file issue to go away)
